// app/api/videos/route.ts
import { NextRequest, NextResponse } from 'next/server';

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams;
  const category = searchParams.get('category');
  const limit = parseInt(searchParams.get('limit') || '10');
  const aiGenerated = searchParams.get('ai') === 'true';
  
  const videos = [
    {
      id: '1',
      title: 'How to Trade Crypto for Beginners',
      creator: 'Crypto University',
      views: 1250000,
      likes: 85000,
      duration: '15:30',
      thumbnail: '🎬',
      category: 'Education',
      uploadedAt: new Date(Date.now() - 86400000).toISOString(),
      sponsor: '0G Labs',
      description: 'Learn crypto trading basics with 0G infrastructure'
    },
    {
      id: '2',
      title: 'AI Revolution in 2024',
      creator: 'Tech Insights',
      views: 850000,
      likes: 42000,
      duration: '22:15',
      thumbnail: '🤖',
      category: 'Technology',
      uploadedAt: new Date(Date.now() - 172800000).toISOString(),
      sponsor: 'Delysium',
      description: 'AI agents and their impact on technology'
    },
    {
      id: '3',
      title: 'Building Web3 Applications with 0G',
      creator: '0G Academy',
      views: 320000,
      likes: 18000,
      duration: '45:20',
      thumbnail: '⚡',
      category: 'Development',
      uploadedAt: new Date(Date.now() - 259200000).toISOString(),
      sponsor: '0G Labs',
      description: 'Complete guide to building on 0G infrastructure'
    },
    {
      id: '4',
      title: 'Creating NFTs with Visual Agent Studio',
      creator: 'Visual Agent Studio',
      views: 480000,
      likes: 32000,
      duration: '18:20',
      thumbnail: '🎨',
      category: 'NFT',
      uploadedAt: new Date(Date.now() - 518400000).toISOString(),
      sponsor: 'Visual Agent Studio',
      description: 'AI-powered NFT creation platform tutorial'
    },
    {
      id: '5',
      title: 'AI Generated: Your Personalized Adventure',
      creator: 'AI Video Generator',
      views: 125000,
      likes: 28000,
      duration: '3:45',
      thumbnail: '🎭',
      category: 'AI Generated',
      uploadedAt: new Date(Date.now() - 43200000).toISOString(),
      isAIGenerated: true,
      aiModel: '0G AI Model v2.1',
      sponsor: '0G Labs',
      description: 'Personalized video generated by 0G AI'
    }
  ];
  
  let filteredVideos = videos;
  
  if (category) {
    filteredVideos = filteredVideos.filter(video => 
      video.category.toLowerCase() === category.toLowerCase()
    );
  }
  
  if (aiGenerated) {
    filteredVideos = filteredVideos.filter(video => video.isAIGenerated);
  }
  
  filteredVideos = filteredVideos.slice(0, limit);
  
  return NextResponse.json({
    success: true,
    data: filteredVideos,
    total: filteredVideos.length,
    hasMore: videos.length > limit,
    timestamp: new Date().toISOString(),
    note: 'Videos powered by sponsor integrations and AI generation'
  });
}

export async function POST(request: NextRequest) {
  try {
    const { action, videoId, ...data } = await request.json();
    
    if (action === 'like') {
      await new Promise(resolve => setTimeout(resolve, 500));
      
      return NextResponse.json({
        success: true,
        videoId,
        action: 'like',
        likes: 85001, // Incremented
        timestamp: new Date().toISOString(),
        message: 'Video liked successfully'
      });
    }
    
    if (action === 'view') {
      await new Promise(resolve => setTimeout(resolve, 300));
      
      return NextResponse.json({
        success: true,
        videoId,
        action: 'view',
        views: 1250001, // Incremented
        timestamp: new Date().toISOString()
      });
    }
    
    return NextResponse.json(
      { success: false, error: 'Invalid action' },
      { status: 400 }
    );
  } catch (error) {
    console.error('Videos API error:', error);
    return NextResponse.json(
      { 
        success: false, 
        error: 'Video operation failed',
        fallback: true
      },
      { status: 500 }
    );
  }
}