/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ChatInterface extends Interface {
  getFunction(
    nameOrSignature: "sendMessage" | "verifyMessage"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "NewMessage"): EventFragment;

  encodeFunctionData(
    functionFragment: "sendMessage",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyMessage",
    values: [AddressLike, AddressLike, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "sendMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyMessage",
    data: BytesLike
  ): Result;
}

export namespace NewMessageEvent {
  export type InputTuple = [
    sender: AddressLike,
    recipient: AddressLike,
    content: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    recipient: string,
    content: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    sender: string;
    recipient: string;
    content: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Chat extends BaseContract {
  connect(runner?: ContractRunner | null): Chat;
  waitForDeployment(): Promise<this>;

  interface: ChatInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  sendMessage: TypedContractMethod<
    [recipient: AddressLike, content: string],
    [void],
    "nonpayable"
  >;

  verifyMessage: TypedContractMethod<
    [
      sender: AddressLike,
      recipient: AddressLike,
      content: string,
      timestamp: BigNumberish
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "sendMessage"
  ): TypedContractMethod<
    [recipient: AddressLike, content: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyMessage"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      recipient: AddressLike,
      content: string,
      timestamp: BigNumberish
    ],
    [boolean],
    "view"
  >;

  getEvent(
    key: "NewMessage"
  ): TypedContractEvent<
    NewMessageEvent.InputTuple,
    NewMessageEvent.OutputTuple,
    NewMessageEvent.OutputObject
  >;

  filters: {
    "NewMessage(address,address,string,uint256)": TypedContractEvent<
      NewMessageEvent.InputTuple,
      NewMessageEvent.OutputTuple,
      NewMessageEvent.OutputObject
    >;
    NewMessage: TypedContractEvent<
      NewMessageEvent.InputTuple,
      NewMessageEvent.OutputTuple,
      NewMessageEvent.OutputObject
    >;
  };
}
