/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Chat } from "./Chat";
export * as factories from "./factories";
export { Chat__factory } from "./factories/Chat__factory";
