/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ForgeFaucet } from "./ForgeFaucet";
export type { ForgeToken } from "./ForgeToken";
export type { ModelRegistry } from "./ModelRegistry";
export type { TestToken } from "./TestToken";
