import { z } from 'zod'
import { AgentApiItem } from '@/lib/types/agents'

export const mockAgents: z.infer<typeof AgentApiItem>[] = [
  {
    id: '1',
    display_name: 'DataMiner Pro',
    bio: '专业数据分析与市场研究 Agent，擅长处理大规模数据集并生成可视化报告',
    avatar: '📊',
    price: 50,
    rating: 4.9,
    completed_tasks: 1234,
    response_time: '< 5分钟',
    tags: ['数据分析', '市场研究', '可视化'],
    is_online: true,
    runtime_type: 'remote_api',
    auth_type: 'platform_hmac',
  },
  {
    id: '2',
    display_name: 'CodeCraft AI',
    bio: '智能代码生成与审核 Agent，支持多种编程语言，专注于安全与性能优化',
    avatar: '💻',
    price: 80,
    rating: 4.8,
    completed_tasks: 892,
    response_time: '< 10分钟',
    tags: ['代码生成', '代码审核', '安全'],
    is_online: true,
    runtime_type: 'remote_api',
    auth_type: 'platform_jwt',
  },
  {
    id: '3',
    display_name: 'ContentGenius',
    bio: '创意内容生成专家，覆盖文案、营销、社交媒体等多种场景',
    avatar: '✍️',
    price: 35,
    rating: 4.7,
    completed_tasks: 2156,
    response_time: '< 3分钟',
    tags: ['内容创作', '营销文案', 'SEO'],
    is_online: true,
    runtime_type: 'remote_api',
  },
  {
    id: '4',
    display_name: 'TradingBot Alpha',
    bio: 'DeFi 交易策略分析与执行 Agent，提供市场洞察和风险评估',
    avatar: '📈',
    price: 150,
    rating: 4.9,
    completed_tasks: 567,
    response_time: '< 1分钟',
    tags: ['DeFi', '交易策略', '风险分析'],
    is_online: false,
    runtime_type: 'remote_api',
  },
  {
    id: '5',
    display_name: 'SmartContract Auditor',
    bio: '智能合约安全审计 Agent，检测漏洞并提供修复建议',
    avatar: '🔐',
    price: 200,
    rating: 5.0,
    completed_tasks: 234,
    response_time: '< 30分钟',
    tags: ['合约审计', '安全检测', 'Solidity'],
    is_online: true,
    runtime_type: 'remote_api',
  },
  {
    id: '6',
    display_name: 'NFT Creator',
    bio: 'NFT 艺术生成与元数据管理 Agent，支持多链部署',
    avatar: '🎨',
    price: 45,
    rating: 4.6,
    completed_tasks: 1876,
    response_time: '< 15分钟',
    tags: ['NFT', '艺术生成', '元数据'],
    is_online: true,
    runtime_type: 'remote_api',
  },
]
