import { z } from 'zod'
import { ArbitrationCase, DaoMember } from '@/lib/types/dao'

export const mockArbitrationCases: z.infer<typeof ArbitrationCase>[] = [
  {
    id: 'arb-1',
    taskId: 'task-1',
    taskTitle: '交易策略回测分析',
    buyerAddress: '0x1234...5678',
    sellerAddress: '0xabcd...efgh',
    amount: 300,
    reason: '买家声称交付的回测报告数据不准确，无法复现所述结果',
    status: 'voting',
    votesForBuyer: 12,
    votesForSeller: 8,
    quorum: 20,
    deadline: 23,
    deadlineDisplay: '剩余 23 小时',
    finalized: false,
    evidence: ['screenshot1.png', 'report.pdf'],
  },
  {
    id: 'arb-2',
    taskId: 'task-2',
    taskTitle: 'API 接口开发',
    buyerAddress: '0x9876...4321',
    sellerAddress: '0xijkl...mnop',
    amount: 180,
    reason: '卖家未按时交付，且交付结果与需求描述不符',
    status: 'resolved_buyer',
    votesForBuyer: 18,
    votesForSeller: 7,
    quorum: 15,
    deadline: 0,
    deadlineDisplay: '已结束',
    finalized: true,
    evidence: ['chat_log.txt', 'requirements.md'],
  },
  {
    id: 'arb-3',
    taskId: 'task-3',
    taskTitle: 'Logo 设计服务',
    buyerAddress: '0xqrst...uvwx',
    sellerAddress: '0xyzab...cdef',
    amount: 50,
    reason: '买家在收到满意结果后仍申请退款',
    status: 'resolved_seller',
    votesForBuyer: 5,
    votesForSeller: 20,
    quorum: 10,
    deadline: 0,
    deadlineDisplay: '已结束',
    finalized: true,
    evidence: ['final_design.png', 'approval_message.txt'],
  },
]

export const mockDaoMembers: z.infer<typeof DaoMember>[] = [
  { address: '0xABC1...1234', votingPower: 1500, avatar: '👨‍⚖️' },
  { address: '0xDEF2...5678', votingPower: 1200, avatar: '👩‍⚖️' },
  { address: '0xGHI3...9ABC', votingPower: 980, avatar: '🧑‍⚖️' },
  { address: '0xJKL4...DEFG', votingPower: 850, avatar: '👨‍💼' },
  { address: '0xMNO5...HIJK', votingPower: 720, avatar: '👩‍💼' },
]
